name: Notion Assistant

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --web-renderer html --csp
      - run: dart compile js lib/background.dart -o build/web/background.js
