name: Notion Assistant

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd background && npm run build
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --web-renderer html --csp
      - run: zip -r release.zip build/web/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: This should change something
          bodyFile: "./release.zip"
          draft: false
          prerelease: false